// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bhbosman/goUi/UiSlides/cmSlide (interfaces: IConnectionSlide)

// Package cmSlide is a generated GoMock package.
package cmSlide

import (
	"context"
	fmt "fmt"

	errors "github.com/bhbosman/gocommon/errors"
)

// Interface A Comment
// Interface github.com/bhbosman/goUi/UiSlides/cmSlide
// Interface IConnectionSlide
// Interface IConnectionSlide, Method: Send
type IConnectionSlideSendIn struct {
	arg0 interface{}
}

type IConnectionSlideSendOut struct {
	Args0 error
}
type IConnectionSlideSendError struct {
	InterfaceName string
	MethodName    string
	Reason        string
}

func (self *IConnectionSlideSendError) Error() string {
	return fmt.Sprintf("error in data coming back from %v::%v. Reason: %v", self.InterfaceName, self.MethodName, self.Reason)
}

type IConnectionSlideSend struct {
	inData         IConnectionSlideSendIn
	outDataChannel chan IConnectionSlideSendOut
}

func NewIConnectionSlideSend(waitToComplete bool, arg0 interface{}) *IConnectionSlideSend {
	var outDataChannel chan IConnectionSlideSendOut
	if waitToComplete {
		outDataChannel = make(chan IConnectionSlideSendOut)
	} else {
		outDataChannel = nil
	}
	return &IConnectionSlideSend{
		inData: IConnectionSlideSendIn{
			arg0: arg0,
		},
		outDataChannel: outDataChannel,
	}
}

func (self *IConnectionSlideSend) Wait(onError func(interfaceName string, methodName string, err error) error) (IConnectionSlideSendOut, error) {
	data, ok := <-self.outDataChannel
	if !ok {
		generatedError := &IConnectionSlideSendError{
			InterfaceName: "IConnectionSlide",
			MethodName:    "Send",
			Reason:        "Channel for IConnectionSlide::Send returned false",
		}
		if onError != nil {
			err := onError("IConnectionSlide", "Send", generatedError)
			return IConnectionSlideSendOut{}, err
		} else {
			return IConnectionSlideSendOut{}, generatedError
		}
	}
	return data, nil
}

func (self *IConnectionSlideSend) Close() error {
	close(self.outDataChannel)
	return nil
}
func CallIConnectionSlideSend(context context.Context, channel chan<- interface{}, waitToComplete bool, arg0 interface{}) (IConnectionSlideSendOut, error) {
	if context != nil && context.Err() != nil {
		return IConnectionSlideSendOut{}, context.Err()
	}
	data := NewIConnectionSlideSend(waitToComplete, arg0)
	if waitToComplete {
		defer func(data *IConnectionSlideSend) {
			err := data.Close()
			if err != nil {
			}
		}(data)
	}
	if context != nil && context.Err() != nil {
		return IConnectionSlideSendOut{}, context.Err()
	}
	channel <- data
	var err error
	var v IConnectionSlideSendOut
	if waitToComplete {
		v, err = data.Wait(func(interfaceName string, methodName string, err error) error {
			return err
		})
	} else {
		err = errors.NoWaitOperationError
	}
	if err != nil {
		return IConnectionSlideSendOut{}, err
	}
	return v, nil
}

// Interface IConnectionSlide, Method: SetConnectionInstanceChange
type IConnectionSlideSetConnectionInstanceChangeIn struct {
	arg0 func(ConnectionInstanceData)
}

type IConnectionSlideSetConnectionInstanceChangeOut struct {
}
type IConnectionSlideSetConnectionInstanceChangeError struct {
	InterfaceName string
	MethodName    string
	Reason        string
}

func (self *IConnectionSlideSetConnectionInstanceChangeError) Error() string {
	return fmt.Sprintf("error in data coming back from %v::%v. Reason: %v", self.InterfaceName, self.MethodName, self.Reason)
}

type IConnectionSlideSetConnectionInstanceChange struct {
	inData         IConnectionSlideSetConnectionInstanceChangeIn
	outDataChannel chan IConnectionSlideSetConnectionInstanceChangeOut
}

func NewIConnectionSlideSetConnectionInstanceChange(waitToComplete bool, arg0 func(ConnectionInstanceData)) *IConnectionSlideSetConnectionInstanceChange {
	var outDataChannel chan IConnectionSlideSetConnectionInstanceChangeOut
	if waitToComplete {
		outDataChannel = make(chan IConnectionSlideSetConnectionInstanceChangeOut)
	} else {
		outDataChannel = nil
	}
	return &IConnectionSlideSetConnectionInstanceChange{
		inData: IConnectionSlideSetConnectionInstanceChangeIn{
			arg0: arg0,
		},
		outDataChannel: outDataChannel,
	}
}

func (self *IConnectionSlideSetConnectionInstanceChange) Wait(onError func(interfaceName string, methodName string, err error) error) (IConnectionSlideSetConnectionInstanceChangeOut, error) {
	data, ok := <-self.outDataChannel
	if !ok {
		generatedError := &IConnectionSlideSetConnectionInstanceChangeError{
			InterfaceName: "IConnectionSlide",
			MethodName:    "SetConnectionInstanceChange",
			Reason:        "Channel for IConnectionSlide::SetConnectionInstanceChange returned false",
		}
		if onError != nil {
			err := onError("IConnectionSlide", "SetConnectionInstanceChange", generatedError)
			return IConnectionSlideSetConnectionInstanceChangeOut{}, err
		} else {
			return IConnectionSlideSetConnectionInstanceChangeOut{}, generatedError
		}
	}
	return data, nil
}

func (self *IConnectionSlideSetConnectionInstanceChange) Close() error {
	close(self.outDataChannel)
	return nil
}
func CallIConnectionSlideSetConnectionInstanceChange(context context.Context, channel chan<- interface{}, waitToComplete bool, arg0 func(ConnectionInstanceData)) (IConnectionSlideSetConnectionInstanceChangeOut, error) {
	if context != nil && context.Err() != nil {
		return IConnectionSlideSetConnectionInstanceChangeOut{}, context.Err()
	}
	data := NewIConnectionSlideSetConnectionInstanceChange(waitToComplete, arg0)
	if waitToComplete {
		defer func(data *IConnectionSlideSetConnectionInstanceChange) {
			err := data.Close()
			if err != nil {
			}
		}(data)
	}
	if context != nil && context.Err() != nil {
		return IConnectionSlideSetConnectionInstanceChangeOut{}, context.Err()
	}
	channel <- data
	var err error
	var v IConnectionSlideSetConnectionInstanceChangeOut
	if waitToComplete {
		v, err = data.Wait(func(interfaceName string, methodName string, err error) error {
			return err
		})
	} else {
		err = errors.NoWaitOperationError
	}
	if err != nil {
		return IConnectionSlideSetConnectionInstanceChangeOut{}, err
	}
	return v, nil
}

// Interface IConnectionSlide, Method: SetConnectionListChange
type IConnectionSlideSetConnectionListChangeIn struct {
	arg0 func([]IdAndName)
}

type IConnectionSlideSetConnectionListChangeOut struct {
}
type IConnectionSlideSetConnectionListChangeError struct {
	InterfaceName string
	MethodName    string
	Reason        string
}

func (self *IConnectionSlideSetConnectionListChangeError) Error() string {
	return fmt.Sprintf("error in data coming back from %v::%v. Reason: %v", self.InterfaceName, self.MethodName, self.Reason)
}

type IConnectionSlideSetConnectionListChange struct {
	inData         IConnectionSlideSetConnectionListChangeIn
	outDataChannel chan IConnectionSlideSetConnectionListChangeOut
}

func NewIConnectionSlideSetConnectionListChange(waitToComplete bool, arg0 func([]IdAndName)) *IConnectionSlideSetConnectionListChange {
	var outDataChannel chan IConnectionSlideSetConnectionListChangeOut
	if waitToComplete {
		outDataChannel = make(chan IConnectionSlideSetConnectionListChangeOut)
	} else {
		outDataChannel = nil
	}
	return &IConnectionSlideSetConnectionListChange{
		inData: IConnectionSlideSetConnectionListChangeIn{
			arg0: arg0,
		},
		outDataChannel: outDataChannel,
	}
}

func (self *IConnectionSlideSetConnectionListChange) Wait(onError func(interfaceName string, methodName string, err error) error) (IConnectionSlideSetConnectionListChangeOut, error) {
	data, ok := <-self.outDataChannel
	if !ok {
		generatedError := &IConnectionSlideSetConnectionListChangeError{
			InterfaceName: "IConnectionSlide",
			MethodName:    "SetConnectionListChange",
			Reason:        "Channel for IConnectionSlide::SetConnectionListChange returned false",
		}
		if onError != nil {
			err := onError("IConnectionSlide", "SetConnectionListChange", generatedError)
			return IConnectionSlideSetConnectionListChangeOut{}, err
		} else {
			return IConnectionSlideSetConnectionListChangeOut{}, generatedError
		}
	}
	return data, nil
}

func (self *IConnectionSlideSetConnectionListChange) Close() error {
	close(self.outDataChannel)
	return nil
}
func CallIConnectionSlideSetConnectionListChange(context context.Context, channel chan<- interface{}, waitToComplete bool, arg0 func([]IdAndName)) (IConnectionSlideSetConnectionListChangeOut, error) {
	if context != nil && context.Err() != nil {
		return IConnectionSlideSetConnectionListChangeOut{}, context.Err()
	}
	data := NewIConnectionSlideSetConnectionListChange(waitToComplete, arg0)
	if waitToComplete {
		defer func(data *IConnectionSlideSetConnectionListChange) {
			err := data.Close()
			if err != nil {
			}
		}(data)
	}
	if context != nil && context.Err() != nil {
		return IConnectionSlideSetConnectionListChangeOut{}, context.Err()
	}
	channel <- data
	var err error
	var v IConnectionSlideSetConnectionListChangeOut
	if waitToComplete {
		v, err = data.Wait(func(interfaceName string, methodName string, err error) error {
			return err
		})
	} else {
		err = errors.NoWaitOperationError
	}
	if err != nil {
		return IConnectionSlideSetConnectionListChangeOut{}, err
	}
	return v, nil
}

func ChannelEventsForIConnectionSlide(next IConnectionSlide, event interface{}) (bool, error) {
	switch v := event.(type) {
	case *IConnectionSlideSend:
		data := IConnectionSlideSendOut{}
		data.Args0 = next.Send(v.inData.arg0)
		if v.outDataChannel != nil {
			v.outDataChannel <- data
		}
		return true, nil
	case *IConnectionSlideSetConnectionInstanceChange:
		data := IConnectionSlideSetConnectionInstanceChangeOut{}
		next.SetConnectionInstanceChange(v.inData.arg0)
		if v.outDataChannel != nil {
			v.outDataChannel <- data
		}
		return true, nil
	case *IConnectionSlideSetConnectionListChange:
		data := IConnectionSlideSetConnectionListChangeOut{}
		next.SetConnectionListChange(v.inData.arg0)
		if v.outDataChannel != nil {
			v.outDataChannel <- data
		}
		return true, nil
	default:
		return false, nil
	}
}
